# Prometheus configuration for GhostChain monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # GhostChain blockchain node
  - job_name: 'ghostd'
    scrape_interval: 10s
    static_configs:
      - targets: ['ghostd:8545']
    metrics_path: '/metrics'
    scheme: 'http'

  # Wallet service
  - job_name: 'walletd'
    scrape_interval: 10s
    static_configs:
      - targets: ['walletd:3001']
    metrics_path: '/metrics'
    scheme: 'http'

  # ZNS resolver
  - job_name: 'zns-resolver'
    scrape_interval: 10s
    static_configs:
      - targets: ['zns-resolver:8548']
    metrics_path: '/metrics'
    scheme: 'http'

  # NGINX metrics
  - job_name: 'nginx'
    scrape_interval: 30s
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/nginx_status'
    scheme: 'http'

  # Redis metrics
  - job_name: 'redis'
    scrape_interval: 30s
    static_configs:
      - targets: ['redis:6379']

  # Node exporter for system metrics (if added)
  - job_name: 'node-exporter'
    scrape_interval: 30s
    static_configs:
      - targets: ['node-exporter:9100']

# Alerting rules
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093